# Generated by Django 5.0.4 on 2024-04-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
