# Generated by Django 5.0.4 on 2024-04-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
