# Generated by Django 5.0.4 on 2024-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является преподавателем', verbose_name='Статус преподавателя'),
        ),
    ]
