# Generated by Django 5.0.4 on 2024-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
        ('CustomUsers', '0006_customuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course_id',
            field=models.ManyToManyField(related_name='user', to='Courses.course'),
        ),
    ]
