# Generated by Django 5.0.4 on 2024-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=150, verbose_name='Курсы')),
                ('course_description', models.TextField(blank=True, max_length=1500, verbose_name='Описание курса')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
