# Generated by Django 5.0.4 on 2024-04-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questions', '0002_alter_question_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(max_length=150, verbose_name='Вариант ответа')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='Questions.question')),
            ],
        ),
    ]
