# Generated by Django 5.0.4 on 2024-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='isCorrect',
            field=models.BooleanField(default=False, verbose_name='Правильный/Неправильный ответ'),
        ),
    ]
