# Generated by Django 5.0.4 on 2024-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_name', models.CharField(max_length=150, verbose_name='Имя теста')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
