# Generated by Django 5.0.4 on 2024-04-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True



    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=150, verbose_name='Название (описание) вопроса')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Testings.testing')),
            ],
        ),
    ]
