# Generated by Django 5.0.4 on 2024-05-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(blank=True, max_length=15000, verbose_name='Содержание курса')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='Chapters.chapter')),
            ],
        ),
    ]
