# Generated by Django 5.0.4 on 2024-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_text',
            field=models.TextField(blank=True, max_length=15000, verbose_name='Содержание главы'),
        ),
    ]
