# Generated by Django 5.0.4 on 2024-05-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(blank=True, max_length=150, verbose_name='Название главы')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='Courses.course')),
            ],
        ),
    ]
