# Generated by Django 5.0.4 on 2024-04-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Answers', '0001_initial'),
        ('Options', '0001_initial'),
        ('Questions', '0002_alter_question_test_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='Options.option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='Questions.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student_id',
            field=models.ManyToManyField(related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
